sudo: required
services:
  - docker

before_install:
  - docker build -t lu23/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true lu23/react-test npm test -- --coverage

after_success:
  - docker build -t lu23/multi-client ./client
  - docker build -t lu23/multi-nginx ./nginx
  - docker build -t lu23/multi-server ./server
  - docker build -t lu23/multi-worker ./worker

  # Log into the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those image and push them to dockerhub
  - docker push lu23/multi-client
  - docker push lu23/multi-nginx
  - docker push lu23/multi-server
  - docker push lu23/multi-worker
